config/routes.rb
HomeworkNotifier::Application.routes.draw do
  root :to => 'groups#index'
  resources :groups do
    collection do
      post "receive_message"
    end
    member do
      post "send_message", :as=>:send_message_to
    end
    resources :students do
    end
  end
  resources :students

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', }, :controllers=>{:confirmations=>"confirmations"}, :skip=>:registrations do
    put "/users/verification", :to=>"confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :group
  has_many :logged_messages, :as=>:sender, :dependent=>:nullify
  #for the moment, we expect standard, US-style 10 digit area code/number. we assume a country code of 1.

  validates_phone_number :phone_number, :allow_blank=>true
  validates_uniqueness_of :phone_number, :scope=>:group_id, :allow_blank=>true, :allow_nil=>true
  
  validates_presence_of :name
  
  validate :notification_method_present?
  
  def notification_method_present?
    errors.add(:base,"either phone_number or email must be present") unless [phone_number,email].any?(&:present?)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :load_group
  
  # GET /students
  # GET /students.xml
  def index
    @students = @group.students
    @student_update = "Now is the time."

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.includes(:groups).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        @group.students << @student unless @group.students.include? @student
        format.html { redirect_to(group_url(@group), :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(group_students_url(@group), :notice => 'Student was successfully updated.') }
        format.js
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(group_students_url(@group)) }
      format.xml  { head :ok }
    end
  end
  
  private
  def load_group
    if params[:group_id]
    @group = Group.find(params[:group_id])
    elsif
      @group = Group.find(params[:student][:group_id])
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<% if @student.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

  <ul>
  <% @student.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name, :class => 'ajax_edit student' %>
</div>
<div class="field">
<%= f.label :phone_number %><br />
<%= f.text_field :phone_number, :class => 'ajax_edit number' %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email, :class => "ajax_edit" %>
</div>
<% #TODO: groups/memberships%>
<%= link_to 'Cancel', group_path(@group), :class => "button secondary minor margin_top" %>
<%= f.submit "Save", :class => 'button minor margin_top' %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= form_for(:student, :url => group_student_path(@group, @student), :html => {:method => :put}) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>
<%= link_to 'Show', group_student_path(@group) %> |
<%= link_to 'Back', group_students_path(@group) %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone number</th>
    <th>Groups</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.phone_number %></td>
    <% #strictly speaking, the .html_safe should be unnecessary. see bug https://rails.lighthouseapp.com/projects/8994/tickets/6298 %>
    <td><%= (student.groups.map {|g| link_to(g.description, g)}*", ").html_safe  %></td>
    <td><%= link_to 'Show', group_student_path(@group.id, student) %></td>
    <td><%= link_to 'Edit', edit_group_student_path(@group.id, student) %></td>
    <td><%= link_to 'Destroy', group_student_path(@group.id, student.id), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_group_student_path(@group.id) %>

app/views/students/new.html.erb
<div id="left_column">
</div>

<div id="right_column">
  <h1>New Member</h1>
  <div class="left">
    <div>
        <%= form_for(:student, :url => group_students_path(@group), :html => {:method => :post}) do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
    </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Phone number:</b>
  <%= @student.phone_number %>
</p>

<p>
  <b>Groups:</b>
  <br />
  <ul>
  <% for group in @student.groups %>
    <li><%= link_to group.title, group_path %></li>
  <% end %>
  </ul>
</p>
<br />

<%= link_to 'Edit', edit_group_student_path(@group, @student) %> |
<%= link_to 'Back', group_students_path(@group) %>

app/views/students/update.js.erb
$("#edit_student_<%= @student.id %>").hide();
$("#student_info_<%= @student.id %>").replaceWith('<%=escape_javascript(render :partial => "groups/member_list" , :locals => {:student => @student, :group => @group, :member => @student} )%>');
$("#edit_student_<%= @student.id %>").replaceWith('<%=escape_javascript(render :partial => "groups/ajax_membership_form" , :locals => {:student => @student, :group => @group} )%>');
$("#student_info_<%= @student.id %>").show();