config/routes.rb
HomeworkNotifier::Application.routes.draw do
  root :to => 'groups#index'
  resources :groups do
    collection do
      post "receive_message"
    end
    member do
      post "send_message", :as=>:send_message_to
    end
    resources :students do
    end
  end
  resources :students

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', }, :controllers=>{:confirmations=>"confirmations"}, :skip=>:registrations do
    put "/users/verification", :to=>"confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  attr_readonly :user_id #after being set, can't change
  
  has_many :students, :dependent=>:destroy
  has_many :logged_messages, :dependent=>:nullify
  
  accepts_nested_attributes_for :students, :allow_destroy=>true, :reject_if=>:all_blank
  
  validates_phone_number :phone_number
  
  def send_message(message,sending_person,recipients=nil)
    recipients ||= students+[user] - [sending_person]
    sms_recipients,other_recipients = recipients.partition {|r| r.phone_number.present?} #in future, partition based on notification preferences AND availability of notifications
    
    #send sms messages to sms recipients
    numbers = sms_recipients.map(&:phone_number)
    $outbound_flocky.message phone_number, message, numbers
    
    #log sms poutputs
    numbers.each do |destination|
      LoggedMessage.create(:group=>self,:sender=>sending_person,:source_phone=>phone_number,:destination_phone=>destination,:message=>message)
    end

    #send message to non-sms recipients (email, for now)
    other_recipients.each {|recip| NotificationMailer.notification_email(message,recip,self)}
    
    #todo: also log these messages
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!, :except=>:receive_message
  before_filter :load_groups

  def index
    @groups = current_user.groups
    @page_title = "Your Groups"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  def show
    @group = current_user.groups.find(params[:id])
    @page_title = @group.title
    @messages = @group.logged_messages.unique_messages.order("created_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  def new
    @group = current_user.groups.new
    @page_title = "New Group"
    @students=[Student.new]*10
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
    @page_title = "#{@group.title}"
    @students = @group.students
  end

  def create
    params[:group][:user_id]=current_user.id
    @group = current_user.groups.new(params[:group])
    @group.phone_number = get_new_phone_number
    @page_title = "New Groups"
    @group.description = "Click to add more info..."
		
    respond_to do |format|
      if @group.save
        format.html { redirect_to(group_path(@group), :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        #TODO: find a better, less API-intensive way to ensure we don't abuse our tropo provisioning
        if @group.phone_number.nil?
          @group.errors[:phone_number] = ["could not provision phone number at this time"]
        else
          destroy_phone_number(@group.phone_number)
          @group.phone_number=nil
        end
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end

  end

  def update
    @group = current_user.groups.find(params[:id])
    @page_title = "#{@group.title}"
    
    respond_to do |format|
      if @group.update_attributes(params[:group])
        @group.reload if @group.students.any?(&:marked_for_destruction?)
        format.html { redirect_to(@group) }
        format.js
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
  

  #POST groups/:id/send_message, sends a message to all members of group
  def send_message
    @group = current_user.groups.find(params[:id])
    message = @group.user.display_name+": "+params[:message][:content] #TODO: safety, parsing, whatever.
    #TODO: ensure group found
    
    if params[:commit].match /scheduled/i
      time_zone = ActiveSupport::TimeZone["Eastern Time (US & Canada)"]  #use eastern time for the input
      scheduled_run = time_zone.local(*params[:date].values_at(*%w{year month day hour}).map(&:to_i))

      #schedule 5 minutes early so we don't accidentally hit anything silly on cron job execution time
      @group.delay(:run_at=>scheduled_run-5.minutes).send_message(message,@group.user)
      pretty_time = scheduled_run.strftime("%A, %B %d, %I:%M %p %Z")
      redirect_to @group, :notice=>"Message successfully scheduled for #{pretty_time}" #if actually successful, or something
    else
      @group.send_message(message,@group.user)
      redirect_to @group, :notice=>"Message sent successfully" #if actually successful, or something
    end

  end
  
  #POST groups/receive_message, receives a message as a JSON post, and figures out what to do with it.
  def receive_message
    params[:incoming_number] = $1 if params[:incoming_number]=~/^1(\d{10})$/
    params[:origin_number] = $1 if params[:origin_number]=~/^1(\d{10})$/
    @group=current_user.groups.find_by_phone_number(params[:incoming_number])
    
    if @group
      sent_by_admin=@group.user.phone_number==params[:origin_number]
      @sending_student = @group.students.find_by_phone_number(params[:origin_number])
      @sending_person = sent_by_admin ? @group.user : @sending_student
      
      if @sending_person
        message = (sent_by_admin ? @group.user.display_name : @sending_student.name)+": "+params[:message]
        @group.send_message(message,@sending_person, sent_by_admin ? @group.students : [@group.user]) #if a student sent it, just send it to teacher. if teacher sent it, push to group
      end
    end
    
    render :text=>"sent", :status=>202
    #needs to return something API-like, yo
  end
  
  def load_groups
    @groups = current_user.groups.all
  end

  private
  def get_new_phone_number
    r=$outbound_flocky.create_phone_number_synchronous("1617")
    if r[:response].code == 200
      return r[:response].parsed_response["href"].match(/\+1(\d{10})/)[1] rescue nil
    end
    
    return nil
  end
  def destroy_phone_number(num)
    $outbound_flocky.destroy_phone_number_synchronous(num)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_ajax_form.html.erb
<%= form_for @group, :html => {:id => 'edit_group', :style =>'display: none;'}, :remote => true do |f| %>
	<%= hidden_field :group, :user_id, :value => current_user.id %>
    <%= f.text_field :title, :class => 'ajax_edit title', :id => 'group_title'%>
    <%= f.text_field :description, :class => 'ajax_edit description', :id => 'group_description'%>
    <%= f.submit 'Save', :class=>"button minor"%>
    <a href="#" id="edit_group_cancel" class="minor button secondary">Cancel</a>
<% end %>

app/views/groups/_ajax_membership_form.html.erb
<%= form_for student, :html => {:method => :put, :id => 'edit_student_'+student.id.to_s, :style =>'display: none;'}, :remote => true do |f| %>
    <%= f.hidden_field :group_id, :value => group.id %>
      <%= f.text_field :name, :class => "ajax_edit student" %>
      <%= f.text_field :phone_number, :class => "ajax_edit number" %>
      <%= f.text_field :email, :class=>"ajax_edit" %>
      
      <%= f.submit 'Save', :class=>"button minor"%>
      <a href="#" id="edit_student_cancel" data="<%= student.id%>" class="button minor secondary">Cancel</a>
<%end%>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= hidden_field :group, :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/groups/_member_list.html.erb
<span id="student_info_<%= member.id %>" onClick="$(this).hide(); $('#edit_student_<%= member.id %>').show();">
    <div id="student_name">
        <span class="text_highlight"><%= member.name %></span>
        <%= link_to 'remove', group_path(@group, :group=>{:students_attributes=>[{:id=>member.id,:_destroy=>1}]}), :confirm => 'Are you sure?', :method => :put, :id => 'remove_member' %>
    </div>
    <div id="student_number">
        <span class="text_highlight"><%= PhoneValidator::OUTPUT_PRINTF%member.phone_number.scan(/\d/) if member.phone_number.present? %></span>
    </div>
    <div>
      <span class="text_highlight"><%= member.email %></span>
    </div>
</span>
<span id="edit_student_info_<%=member.id%>">
    <%=render :partial => "groups/ajax_membership_form", :locals => {:student => member, :group => @group}%>
</span>

app/views/groups/_membership_form.html.erb
<%= form_for @group do |f| %>

  <%= f.fields_for :students do |sf|%>

    <div class="field">
      <%= sf.label :name %><br />
      <%= sf.text_field :name, :class => "membership_field" %>
    </div>
    <div class="field">
      <%= sf.label :phone_number %><br />
      <%= sf.text_field :phone_number, :class => "membership_field" %>
    </div>
    <br />
  
  <%end%>

  <div class="actions">
    <%= f.submit %>
  </div>
<%end%>

app/views/groups/_send_message.html.erb
<script type="text/javascript">
	$(document).ready(function()
	{
		$("#message_content").keyup(function()
		{
		var box=$(this).val();
		var main = box.length *100;
		var value= (main / <%= 158 - current_user.display_name.length %>);
		var count= box.length;

		if(box.length <= <%= 158 - current_user.display_name.length %>)
		{
			$('#count').html(count + ' / ' + <%= 158 - current_user.display_name.length %>);
			$('#bar').animate(
				{
				"width": value+'%',
				}, 1);
		}
		return false;
		});
	});
</script>

<%= render :partial => 'ajax_form' %>
<div>
    <div id="group_info" onClick="$(this).hide(); $('#edit_group').show();">
        <h3>
            <span class='title text_highlight'><%= @group.title %></span>
        </h3>
        <h5>
            <span class="left text_highlight"><h5><%= @group.description %></span>
        </h5>
    </div>
    <div id="group_number">
        <h3 class="right">
            <%= PhoneValidator::OUTPUT_PRINTF%@group.phone_number.scan(/\d/) %>
        </h3>
    </div
</div>

<%= form_for @group, :url=>send_message_to_group_path, :html=>{:method=>"post"} do |f| %>
  <%= fields_for :message do |mf| %>
    <div class="field left">
      <%= mf.label :content, "Send Message" %>
			<br />
      <span class="formwrap"><%= mf.text_area :content, :id => "message_content"%>
	<div id="character_count"><h5>
		<div>
			<div id="barbox">
				<div id="bar"></div>
			</div>
		</div>
		<div id="count">0 / <%= 158 - current_user.display_name.length %></div>
	</h5></div>
	</span>
    </div>
  <%end%>
  <div>
      <div id="message_send_options">
          <div class="left"><%= f.submit "Send Message Now", :class => 'button', :id => 'send_message_now' %></div>
          <div>
              <span class="right"><%= select_datetime(DateTime.now,:discard_minute=>true, :start_year=>Date.today.year,:end_year=>Date.today.year+1) %></span>
              <%= f.submit "Send Message at Above Scheduled Time", :class => 'right button secondary', :id => 'send_message_scheduled'%>
          </div>
    </div>
  </div>
<%end%>

app/views/groups/edit.html.erb
<table>
	<tr>
		<td class="top"><%= render 'form' %></td>
		<td class="top"><%= render 'membership_form' %></td>
	</tr>
</table>

<%= link_to 'Back', groups_path %>

app/views/groups/edit_memberships.html.erb
<div id="left_column">
	<%= render :partial => 'send_message' %>
</div>

<div id="right_column">
	<%= form_for(@group,:url=>:update_memberships_of_group) do |f| %>
	  <% @students.each_with_index do |student, index| %>
	  	<% student.id = nil %>
	    <%= fields_for("students[]",student) do |sf| %>
	      <% if student.errors.any? %>
	        <div id="error_explanation">
	          <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>
	            <ul>
	              <% student.errors.full_messages.each do |msg| %>
	                <li><%= msg %></li>
	              <% end %>
	            </ul>
	        </div>
	      <%end%>
    	<div class="gray_outline">
	      <div class="field">
	        <%= sf.label :name %><br />
	        <%= sf.text_field :name, :class => "membership_field last" %>
	      </div>
	      <div class="field">
	        <%= sf.label :phone_number %><br />
	        <%= sf.text_field :phone_number, :class => "membership_field" %>
	      </div>
		</div>
	    <%end%>
	  <%end%>

	  <div class="actions">
	    <%= f.submit "Save Changes", :class => "button secondary right", :disable_with => "Wait..." %>
	  </div>
	<%end%>
</div>

app/views/groups/index.html.erb
<% if @groups.blank? %>
	<h3>You haven't yet created any groups.</h3><br><%= link_to 'Make my first group!', new_group_path, :class => "button" %>
<% else %>
			<% @groups.each do |group| %>
				<a class="group_list_item" href="<%= group_path(group) %>">
							<span class="left">
								<span class="groups primary"><%= group.title %></span><br>
								<span class="groups secondary"><%= group.description %></span>
							</span>
							<span class="right">
								<span class="groups primary"><%= PhoneValidator::OUTPUT_PRINTF%group.phone_number.scan(/\d/) %></span><br>
								<span class="groups secondary right"><%= pluralize group.students.count, "member" %></span>
							</span>
				</a>
			<% end %>
			<br>
	<%= link_to "Add New Group", new_group_path, :class => 'button right' %>
	<div id="return_to_groups"></div>
<% end %>

app/views/groups/new.html.erb
<%= render 'form' %>
<br />
<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div id="right_column">
    <% if @group.students.blank? %>
    	<h5>There are no members in this group.</h5>
    	<%= link_to 'Add Member', new_group_student_path(@group), :class => 'button left minor margin_top' %>

    <% else %>
    	<h5>Your message will be sent to <%= pluralize @group.students.count, "member" %>:</h5>
    	<ul id="student_list">
        <% for member in @group.students %>
        	<li>
        	    <%= render :partial => 'member_list' , :locals => {:member => member}%>
        	</li>
        <% end %>
        <li>
          <%= link_to 'Add Member', new_group_student_path(@group), :class => 'button minor left margin_top' %>
        </li>
      </ul>
    <% end %>
</div>
<div id="left_column">
	<div>
	    <%= render :partial => 'send_message' %>
	</div>
	<div id="return_to_groups"></div>
	<div class="left margin_top">
        <h3>Sent Messages</h3>
        <table id="messages">
        	<tr><th>Sent On</th><th>Message</th></tr>
        	<% @messages.each do |message| %>
        		<tr><td><%=formatted_time(message.created_at) %></td><td><%= message.message %></td></tr>
        	<%end%>
        </table>
        <div id="return_to_groups"></div>
        <span><%= link_to "< All Groups", groups_path %></span>
        <div id="return_to_groups"></div>
    </div>
</div>

app/views/groups/update.js.erb
$("#edit_group").hide();
$("#group_name").replaceWith(" <a href='<%=group_url(@group)%>' class = 'white' id = 'group_name'> <%=@group.title%> </a>");
$("#group_info span.title").replaceWith("<span class='title text_highlight'><%= @group.reload.title %></span>");
$("#group_info span.left").replaceWith("<span class='left text_highlight'><%= @group.reload.description %></span>");
$("#edit_group").replaceWith('<%=escape_javascript(render :partial => "ajax_form" )%>');
$("#group_info").show();