config/routes.rb
HomeworkNotifier::Application.routes.draw do
  root :to => 'groups#index'
  resources :groups do
    collection do
      post "receive_message"
    end
    member do
      post "send_message", :as=>:send_message_to
    end
    resources :students do
    end
  end
  resources :students

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', }, :controllers=>{:confirmations=>"confirmations"}, :skip=>:registrations do
    put "/users/verification", :to=>"confirmations#update", :as=>:update_user_confirmation
  end
  as :user do
    scope "/users" do
      resource :profile, :controller=>"registrations", :only=>[:edit,:update] do
        get "edit_password", :as=>"edit_password_of"
      end
    end
  end

end

app/views/layouts/_breadcrumbs.html.erb
<h2 class="oswald" >
    <% if current_user %>	
        <%= link_to "Groups", groups_url, :class => 'white' %>
    	<% if (params[:controller] == 'groups') && (params[:action] == 'new' || params[:action] == 'create') %>
    		> New Group
    	<% elsif (params[:controller] == 'groups') && (params[:action] == 'edit' || params[:action] == 'update' || params[:action] == 'show' || params[:action] == 'edit_memberships') %>
    		> <%= link_to "#{@group.title}", group_url(@group), :class => 'white', :id => "group_name" %>
    		<% if params[:action] == 'edit' %>
    			> Edit Group
    		<% elsif params[:action] == 'edit_memberships' %>
    			> Edit Members
    		<% end %>
    	<% elsif params[:controller] == 'students' %>
    		> <%= link_to "#{@group.title}", group_url(@group), :class => 'white' %>
    		<% if params[:action] == 'edit' || params[:action] == 'update' %>
    			<span class="noclick">> Edit Member</span>
    		<% elsif params[:action] == 'new' || params[:action] == 'create' %>
    			<span class="noclick">> Add Member</span>
    		<% end %>
    	<% end %>
    <% else %>
        <span class="noclick">Homework Notifier</span>
    <% end %>
</h2>

app/views/layouts/_notices.html.erb
<% if notice.present? %>
	<div class="flash" id="notice"><%= notice %></div>
<% end %>
<% if alert.present? %>
	<div class="flash" id="alert"><%= alert %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd"> 
 
<html lang="en"> 
<head> 
	<title>Homework Notifier</title>  
  <%= stylesheet_link_tag 'reset.css' %>
  <link href='http://fonts.googleapis.com/css?family=Luckiest+Guy' rel='stylesheet' type='text/css'> 
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'> 
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans:regular,bold' rel='stylesheet' type='text/css'> 
  <%= stylesheet_link_tag 'application.css' %>
	<%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head> 
<body>
  <script type="text/javascript" charset="utf-8">
    var is_ssl = ("https:" == document.location.protocol);
    var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
    document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
  </script>

  <script type="text/javascript" charset="utf-8">
    var feedback_widget_options = {};

    feedback_widget_options.display = "overlay";  
    feedback_widget_options.company = "code_for_america";
    feedback_widget_options.placement = "left";
    feedback_widget_options.color = "#2ea390";
    feedback_widget_options.style = "problem";
    feedback_widget_options.product = "code_for_america_homework_notifier";




    feedback_widget_options.limit = "3";


    var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
  </script>
  <div id="container"> 
    <div id="logo" class="top_bar">
  		<a href="/" id="logo_text" class="lucky">ClassTalk</a>
    </div>
    <div id="nav" class="top_bar">
      <% if current_user %>
				<span id="welcome_user">Welcome, <%= current_user.name %></span>
			<% end %>
        <ul id="main_menu">
            <h3>
              <% if current_user %>
                <li><%= link_to "Sign out", destroy_user_session_path %></li>
        				<li><%= link_to "Profile", edit_profile_path %></li>
        			<% else %>
            		<li id="sign_in"><%= link_to('SIGN IN', new_user_session_path)%></li>
        			<% end %>
        			<li><%= link_to "Groups", groups_path %></li>
              <li><a href="http://codeforamerica.org/?cfa_project=whatsassign-me" class="nav_links">ABOUT</a></li>
            </h3>
        </ul>
  </div>
		<div id="main">
			<div class="header">
				<div class="title_text">
					<%= render :partial => 'layouts/breadcrumbs' %>
				</div>
			</div>
			<div class="content">
				<%= render :partial => 'layouts/notices' %>
				<%= yield %>
			</div>
		</div>
  </div>
  <div id="footer">
    <span>made by <a href="http://codeforamerica.org">Code for America</a> in partnership with the <a href="http://www.newurbanmechanics.org">City of Boston</a></span>
	</div>
</body> 
</html>